# Generated by Django 2.0.2 on 2018-02-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_set',
            field=models.CharField(default="I don't have any.", max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('1 - 5 years', '1 - 5 years'), ('6 - 13 years', '6 - 13 years'), ('14 - 20 years', '14 - 20 years'), ('20 years and above', '20 years and above')], max_length=100, null=True),
        ),
    ]
