# Generated by Django 2.0.2 on 2018-02-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180212_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Investor', 'Investor'), ('StartUp', 'StartUp')], max_length=100, null=True),
        ),
    ]
