# Generated by Django 2.0.2 on 2018-02-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='dashboard',
            new_name='dashboard_image',
        ),
    ]
