# Generated by Django 2.0.2 on 2018-02-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180210_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech Automobile'), ('Tech', 'Tech Medical'), ('Tech', 'Tech Agriculture'), ('Tech', 'Tech Ecommerce'), ('Tech', 'Tech Computing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
