# Generated by Django 2.0.2 on 2018-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180211_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
