# Generated by Django 2.0.2 on 2018-02-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20180211_1435'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startup',
            unique_together={('company_name', 'slug')},
        ),
    ]
