# Generated by Django 2.0.2 on 2018-02-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20180212_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='do_you_have_a_3_to_5_year_plan',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
    ]
