# Generated by Django 2.0.2 on 2018-02-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180212_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='resgistered',
            new_name='registered',
        ),
    ]
